# Este es un ejemplo de cómo se vería la lógica de tus imágenes en un archivo de GitHub Actions

name: 'Traducción de GitLab a GitHub Actions'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # ---- Este job simula la "stage: build" ----
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Compiling the code..."
      - run: echo "Compile complete."

  # ---- Estos 2 jobs simulan la "stage: test" ----
  # Ambos dependen de que 'build-job' termine y corren en paralelo entre sí.
  unit-test-job:
    runs-on: ubuntu-latest
    needs: build-job # <-- Le dice a GitHub que este job necesita que 'build-job' termine primero.
    steps:
      - run: echo "Running unit tests... This will take about 60 seconds."
      - run: sleep 60
      - run: echo "Code coverage is 90%"

  lint-test-job:
    runs-on: ubuntu-latest
    needs: build-job # <-- También depende de 'build-job'. Como ambos dependen de lo mismo, corren en paralelo.
    steps:
      - run: echo "Linting code... This will take about 10 seconds."
      - run: sleep 10
      - run: echo "No lint issues found."

  # ---- Este job simula la "stage: deploy" ----
  deploy-job:
    runs-on: ubuntu-latest
    # Le dice a GitHub que espere a que AMBOS jobs de prueba terminen exitosamente.
    needs: [unit-test-job, lint-test-job] 
    steps:
      - run: echo "Deploying application..."
      - run: echo "Application successfully deployed."
